version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_php
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./app:/usr/share/nginx/app
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: [ "db" ]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports: [ "8080:80" ]
    depends_on: [ "php" ]

volumes:
  mysql:
